binary_name := formats_test_vt
dirs.root := ../../../../..
source_dirs := .

libraries.common = binary binary_compression binary_format debug formats_archived formats_chiptune formats_packed strings tools

libraries.3rdparty = lhasa lzma unrar zlib

libraries.windows := advapi32

include $(dirs.root)/makefile.mak
