binary_name := formats_test_vt
path_step := ../../../../..
source_files := test

libraries := tools formats_chiptune binary
depends := src/formats/chiptune src/binary src/tools

windows_libraries := advapi32

include $(path_step)/makefile.mak
