library_name := ui_conversion
path_step := ../../../..

source_dirs := .

moc_files = backend_settings
ui_files = filename_template setup_conversion supported_formats mp3_settings ogg_settings flac_settings

ts_files := ui_conversion

include_dirs = ../..

include $(path_step)/makefile.mak
