library_name := ui_conversion
path_step := ../../../..

moc_files = backend_settings
ui_files = filename_template \
            setup_conversion \
            supported_formats

ui_headeronly = mp3_settings ogg_settings
source_files += $(ui_headeronly)

include_dirs = ../..

include $(path_step)/makefile.mak
