binary_name := xtractor
path_step := ../../../..
source_files := main

libraries := analysis async binary formats io tools 
depends := src/analysis src/async src/binary src/formats src/io src/tools

boost_libraries := thread

windows_libraries := advapi32

include $(path_step)/makefile.mak
