binary_name := formats_test_zxzip
path_step := ../../../..
source_files := test

libraries := io formats binary tools
depends := src/formats src/io src/binary src/tools

windows_libraries := advapi32

include $(path_step)/makefile.mak
