binary_name := formats_test_zxzip
path_step := ../../../..
source_files := test

libraries := formats_packed binary tools
depends := src/formats/packed src/binary src/tools

include $(path_step)/makefile.mak
