all test:
	$(MAKE) -C ../src/analysis/test $(MAKECMDGOALS)
	$(MAKE) -C ../src/async/test $(MAKECMDGOALS)
	$(MAKE) -C ../src/binary/test $(MAKECMDGOALS)
	$(MAKE) -C ../src/formats/test $(MAKECMDGOALS)
	$(MAKE) -C ../src/io/test $(MAKECMDGOALS)
	$(MAKE) -C ../src/sound/test $(MAKECMDGOALS)
	$(MAKE) -C ../src/tools/test $(MAKECMDGOALS)
