binary_name := formats_test_zip
dirs.root := ../../../..
source_dirs := .

libraries.common = binary binary_compression binary_format debug formats_archived formats_packed strings tools
libraries.3rdparty = zlib

include $(dirs.root)/makefile.mak
