binary_name := formats_test_zip
path_step := ../../../..
source_files := test

libraries := binary debug formats_archived formats_packed tools z
depends := src/formats/archived src/debug src/formats/packed src/binary src/tools 3rdparty/zlib

include $(path_step)/makefile.mak
