binary_name := formats_test_zip
path_step := ../../../..
source_files := test

libraries.common = binary debug formats_archived formats_packed tools
libraries.3rdparty = zlib

include $(path_step)/makefile.mak
