binary_name := formats_test_st
path_step := ../../../../..
source_dirs := .

libraries.common = binary binary_format debug formats_chiptune tools

windows_libraries := advapi32

include $(path_step)/makefile.mak
