binary_name := xtractor
path_step := ../..
source_files := main

text_files := text/text

libraries := analysis async binary formats io tools zxtune_app_version
depends := src/analysis src/async src/binary src/formats src/io src/tools apps/version

boost_libraries := filesystem program_options thread system

windows_libraries := advapi32

include $(path_step)/makefile.mak
