binary_name := formats_test_rar
path_step := ../../../..
source_files := test

libraries := binary debug formats_archived formats_packed tools unrar
depends := src/binary src/debug src/formats/archived src/formats/packed src/tools 3rdparty/unrar

include $(path_step)/makefile.mak
