binary_name := formats_test_rar
dirs.root := ../../../..
source_dirs := .

libraries.common = binary binary_compression binary_format debug \
                   formats_archived \
                   strings tools

libraries.3rdparty = lhasa lzma unrar zlib

include $(dirs.root)/makefile.mak
