binary_name := formats_test_rar
path_step := ../../../..
source_files := test

libraries := io formats tools
depends := src/formats src/io src/tools

windows_libraries := advapi32

include $(path_step)/makefile.mak
