binary_name := snd_backend_test
path_step := ../..
source_files := test

libraries := core sound io tools texts
depends := src/core src/io src/sound src/tools text

boost_libraries := thread

include $(path_step)/makefile.mak
