binary_name := snd_backend_test
path_step := ../..
source_files := test

libraries := core devices sound io tools
depends := src/core src/devices src/io src/sound src/tools

boost_libraries := thread

include $(path_step)/makefile.mak
