library_name := formats_image
dirs.root := ../../..
source_dirs := .

include $(dirs.root)/make/default.mak

text_files := ../text/image

jumbo.name := $(library_name)

include $(dirs.root)/makefile.mak
