// Generated from '$Id$'
#ifndef __TEXT_BACKENDS_H_DEFINED__
#define __TEXT_BACKENDS_H_DEFINED__
#include <char_type.h>

namespace Text
{
extern const Char ALSA_BACKEND_DESCRIPTION[];
extern const Char AYLPT_BACKEND_DESCRIPTION[];
extern const Char DSOUND_BACKEND_DESCRIPTION[];
extern const Char FILE_BACKEND_DEFAULT_COMMENT[];
extern const Char NULL_BACKEND_DESCRIPTION[];
extern const Char OSS_BACKEND_DESCRIPTION[];
extern const Char SDL_BACKEND_DESCRIPTION[];
extern const Char SOUND_ERROR_ALSA_BACKEND_DEVICE_ERROR[];
extern const Char SOUND_ERROR_ALSA_BACKEND_ERROR[];
extern const Char SOUND_ERROR_ALSA_BACKEND_INVALID_BUFFERS[];
extern const Char SOUND_ERROR_ALSA_BACKEND_NO_MIXER[];
extern const Char SOUND_ERROR_AYLPT_BACKEND_DUMP[];
extern const Char SOUND_ERROR_DSOUND_BACKEND_ERROR[];
extern const Char SOUND_ERROR_DSOUND_BACKEND_INVALID_LATENCY[];
extern const Char SOUND_ERROR_FILE_BACKEND_NO_FILENAME[];
extern const Char SOUND_ERROR_OSS_BACKEND_ERROR[];
extern const Char SOUND_ERROR_SDL_BACKEND_ERROR[];
extern const Char SOUND_ERROR_SDL_BACKEND_INVALID_BUFFERS[];
extern const Char SOUND_ERROR_SDL_BACKEND_UNKNOWN_ERROR[];
extern const Char SOUND_ERROR_WIN32_BACKEND_ERROR[];
extern const Char SOUND_ERROR_WIN32_BACKEND_INVALID_BUFFERS[];
extern const Char WAV_BACKEND_DESCRIPTION[];
extern const Char WIN32_BACKEND_DESCRIPTION[];
}//namespace Text
#endif //__TEXT_BACKENDS_H_DEFINED__
