library_name := playlist_ui_embedded
path_step := ../../../../..

source_files := playlist_contextmenu_stub.cpp search_dialog_stub.cpp

use_qt = 1

include_dirs = ../../..

include $(path_step)/makefile.mak
