# XSPF versions:
# 0 - initial, no ATTRIBUTE_VERSION tag in playlist properties
# 1 - 'percenting' all the text fields

library_name := playlist_io
path_step := ../../../..

source_files := container_impl import import_ayl import_xspf export_xspf

text_files := tags/xspf tags/ayl

include_dirs = ../..

include $(path_step)/makefile.mak
