library_name := playlist_io
path_step := ../../../..

source_files := container_impl import import_ayl import_xspf

text_files := tags/xspf tags/ayl

include_dirs = ../..

include $(path_step)/makefile.mak
