# XSPF versions:
# 0 - initial, no ATTRIBUTE_VERSION tag in playlist properties
# 1 - 'percenting' all the text fields

library_name := playlist_io
dirs.root := ../../../..

use_qt := 1

source_dirs := .

include $(dirs.root)/makefile.mak
