binary_name := async_test_job
path_step := ../../../..
source_files := test

libraries := async tools
depends := src/async src/tools

boost_libraries := thread system

include $(path_step)/makefile.mak
