binary_name := async_test_job
path_step := ../../../..
source_files := test

libraries := async l10n_stub tools
depends := src/async src/l10n/stub src/tools

boost_libraries := thread

include $(path_step)/makefile.mak
