binary_name := binary_test_compression
dirs.root := ../../../..
source_dirs := .

libraries.common = binary binary_compression strings tools

libraries.3rdparty = zlib

include $(dirs.root)/makefile.mak
