import os
import sys

def read_binaries(paths):
  entries = dict()
  for entry in paths:
    name = os.path.basename(entry)
    with open(entry, 'rb') as fp:
      entries[name] = fp.read()
  return entries

def dump_bin(blob, output):
  print('"', file=output, end='')
  for b in blob:
    print('\\x%02x' % int(b), file=output, end='')
  print('"', file=output, end='')

def dump_binaries(binaries, output):
  print(f"// This file is autogenerated\n// {len(binaries)} entries", file=output)
  for name in sorted(binaries.keys()):
    print(f'{{"{name}"sv,', file=output, end='')
    dump_bin(binaries[name], output)
    print("sv},", file=output)

if __name__ == '__main__':
  binaries = read_binaries(sys.argv[1:])
  dump_binaries(binaries, sys.stdout)
