binary_name := core_test
path_step := ../..
source_files := test

libraries := core io tools texts
depends := src/tools src/core src/io text

windows_libraries := advapi32.lib

include $(path_step)/makefile.mak
