binary_name := libzxtune_test
dirs.root := ../../..
source_files := test.cpp

includes.dirs += $(dirs.root)/apps/libzxtune
libraries.dynamic = zxtune
libraries.windows += delayimp

include $(dirs.root)/makefile.mak
