binary_name := libzxtune_test
path_step := ../../..
source_files := test.cpp

include_dirs += $(path_step)/apps/libzxtune
dynamic_libs = zxtune
libraries.windows += delayimp

include $(path_step)/makefile.mak
