binary_name := zxtune
path_step := ../../..
source_files := test

include_dirs += $(path_step)/apps/libzxtune
dynamic_libs = zxtune
libraries = z
windows_libraries = delayimp

include $(path_step)/makefile.mak
