binary_name := zxtune-qt_test_updates
path_step := ../../../..
source_files := test

libraries.common = tools
libraries.qt := Core

libraries := check_update
depends := apps/zxtune-qt/update

include $(path_step)/makefile.mak
