binary_name := zxtune-qt_test_updates
path_step := ../../../..
source_dirs := .

libraries.common = debug tools
libraries.qt := Core

libraries := check_update
depends := apps/zxtune-qt/update

include $(path_step)/makefile.mak
