binary_name := zxtune-qt_test_updates
path_step := ../../../..
source_files := test

qt_libraries := Core

libraries := check_update tools
depends := apps/zxtune-qt/update src/tools

include $(path_step)/makefile.mak
