library_name := playlist_supp
path_step := ../../../..

source_files := data_provider operations_convert operations_helpers operations_search operations_statistic session storage
moc_files := container controller operations model scanner

include_dirs = ../..

include $(path_step)/makefile.mak
