library_name := playlist_supp
path_step := ../../../..

source_files := data_provider source_file source_container
moc_files := container controller model scanner

include_dirs = ../..

include $(path_step)/makefile.mak
