library_name := playlist_supp
path_step := ../../../..

source_files := data_provider operations_convert session source_file storage
moc_files := container controller operations model scanner

include_dirs = ../..

include $(path_step)/makefile.mak
