binary_name := formats_test_xsf
path_step := ../../../../..
source_dirs := .

libraries.common = binary binary_format debug formats_chiptune strings tools

libraries.3rdparty = zlib

windows_libraries := advapi32

include $(path_step)/makefile.mak
