binary_name := aycli
dirs.root := ../../../..
source_dirs := .

libraries.common = async debug devices_aym l10n_stub parameters platform sound sound_backends_winstub strings tools

libraries.windows = ole32 user32
libraries.mingw = ole32

include $(dirs.root)/makefile.mak
