binary_name := aycli
path_step := ../../../..
source_files := main

libraries.common = async binary core debug devices_aym io l10n_stub parameters platform sound sound_backends strings tools

libraries.boost = filesystem system thread

windows_libraries = advapi32 ole32 user32
mingw_libraries = ole32

include $(path_step)/makefile.mak
