binary_name := aycli
path_step := ../../../..
source_dirs := .

libraries.common = async core debug devices_aym l10n_stub parameters platform sound sound_backends strings tools

windows_libraries = ole32 user32
mingw_libraries = ole32

include $(path_step)/makefile.mak
