/*
Abstract:
  FLAC api gate interface

Last changed:
  $Id$

  This file is automatically generated. Do not edit!
*/

#ifndef SOUND_BACKENDS_FLAC_API_H_DEFINED
#define SOUND_BACKENDS_FLAC_API_H_DEFINED

//platform-dependent includes
#include <FLAC/metadata.h>
#include <FLAC/stream_encoder.h>
//boost includes
#include <boost/shared_ptr.hpp>

namespace Sound
{
  namespace Flac
  {
    class Api
    {
    public:
      typedef boost::shared_ptr<Api> Ptr;
      virtual ~Api() {}

      
      virtual FLAC__StreamEncoder* FLAC__stream_encoder_new(void) = 0;
      virtual void FLAC__stream_encoder_delete(FLAC__StreamEncoder *encoder) = 0;
      virtual FLAC__bool FLAC__stream_encoder_set_verify(FLAC__StreamEncoder *encoder, FLAC__bool value) = 0;
      virtual FLAC__bool FLAC__stream_encoder_set_channels(FLAC__StreamEncoder *encoder, unsigned value) = 0;
      virtual FLAC__bool FLAC__stream_encoder_set_bits_per_sample(FLAC__StreamEncoder *encoder, unsigned value) = 0;
      virtual FLAC__bool FLAC__stream_encoder_set_sample_rate(FLAC__StreamEncoder *encoder, unsigned value) = 0;
      virtual FLAC__bool FLAC__stream_encoder_set_compression_level(FLAC__StreamEncoder *encoder, unsigned value) = 0;
      virtual FLAC__bool FLAC__stream_encoder_set_blocksize(FLAC__StreamEncoder *encoder, unsigned value) = 0;
      virtual FLAC__bool FLAC__stream_encoder_set_metadata(FLAC__StreamEncoder *encoder, FLAC__StreamMetadata **metadata, unsigned num_blocks) = 0;
      virtual FLAC__StreamEncoderInitStatus FLAC__stream_encoder_init_stream(FLAC__StreamEncoder *encoder, FLAC__StreamEncoderWriteCallback write_callback, FLAC__StreamEncoderSeekCallback seek_callback, FLAC__StreamEncoderTellCallback tell_callback, FLAC__StreamEncoderMetadataCallback metadata_callback, void *client_data) = 0;
      virtual FLAC__bool FLAC__stream_encoder_finish(FLAC__StreamEncoder *encoder) = 0;
      virtual FLAC__bool FLAC__stream_encoder_process_interleaved(FLAC__StreamEncoder *encoder, const FLAC__int32 buffer[], unsigned samples) = 0;
      virtual FLAC__StreamMetadata* FLAC__metadata_object_new(FLAC__MetadataType type) = 0;
      virtual void FLAC__metadata_object_delete(FLAC__StreamMetadata *object) = 0;
      virtual FLAC__bool FLAC__metadata_object_vorbiscomment_entry_from_name_value_pair(FLAC__StreamMetadata_VorbisComment_Entry *entry, const char *field_name, const char *field_value) = 0;
      virtual FLAC__bool FLAC__metadata_object_vorbiscomment_append_comment(FLAC__StreamMetadata *object, FLAC__StreamMetadata_VorbisComment_Entry entry, FLAC__bool copy) = 0;
      virtual FLAC__StreamEncoderState 	FLAC__stream_encoder_get_state(const FLAC__StreamEncoder *encoder) = 0;
    };

    //throw exception in case of error
    Api::Ptr LoadDynamicApi();

  }
}

#endif //SOUND_BACKENDS_FLAC_API_H_DEFINED
