#stub library for lha functionality without formats_packed linking
library_name := formats_packed_lha
path_step := ../../../..
source_files := ../lha_file

include $(path_step)/make/default.mak

include $(path_step)/makefile.mak
