#stub library for lha functionality without formats_packed linking
library_name := formats_packed_lha
dirs.root := ../../../..
source_files := ../lha_file.cpp ../container.cpp

include $(dirs.root)/make/default.mak

jumbo.name := $(library_name)

include $(dirs.root)/makefile.mak
