binary_name := platform_test
dirs.root := ../../..
source_dirs := .

libraries.common = debug l10n platform strings tools

libraries.boost += locale
libraries.darwin += iconv

include $(dirs.root)/makefile.mak
