binary_name := io_test_file
path_step := ../../../..
source_dirs := .

libraries.common = binary io l10n_stub platform tools

windows_libraries := advapi32

libraries.boost := filesystem

include $(path_step)/makefile.mak
