binary_name := io_test_file
path_step := ../../../..
source_files := test

libraries := binary io l10n_stub tools
depends := src/binary src/tools src/l10n/stub src/io

windows_libraries := advapi32

boost_libraries := filesystem system

include $(path_step)/makefile.mak
