binary_name := io_test_file
path_step := ../../../..
source_files := test

libraries := binary io tools
depends := src/binary src/tools src/io

windows_libraries := advapi32

include $(path_step)/makefile.mak
