binary_name := mtctool
dirs.root := ../../..
source_dirs := .

libraries.common = binary binary_compression binary_format debug formats_chiptune formats_packed module platform_version strings tools

libraries.3rdparty = lhasa unrar zlib

include $(dirs.root)/makefile.mak
