library_name := playlist_ui
path_step := ../../../..
ui_files := container_view scanner_view filename_template
ui_headeronly := no_items_contextmenu single_item_contextmenu multiple_items_contextmenu
moc_files := playlist_view playlist_contextmenu table_view

include_dirs = ../..

include $(path_step)/makefile.mak
