library_name := playlist_ui
path_step := ../../../..

source_dirs := .

ui_files := container_view scanner_view
moc_files := playlist_view table_view

ts_files := playlist_ui

includes.dirs += ../..

include $(path_step)/makefile.mak
