binary_name := formats_test_lha
path_step := ../../../..
source_files := test

libraries := binary formats_archived formats_packed tools lhasa
depends := src/formats/archived src/formats/packed src/binary src/tools 3rdparty/lhasa/lib

windows_libraries = oldnames

include $(path_step)/makefile.mak
