binary_name := formats_test_lha
path_step := ../../../..
source_files := test

libraries.common = binary debug formats_archived formats_packed tools
libraries.3rdparty = lhasa

windows_libraries = oldnames

include $(path_step)/makefile.mak
