binary_name := formats_test_lha
path_step := ../../../..
source_dirs := .

libraries.common = binary binary_format debug formats_archived formats_packed strings tools
libraries.3rdparty = lhasa

windows_libraries = oldnames

include $(path_step)/makefile.mak
