binary_name := async_test_activity
path_step := ../../../..
source_files := test

libraries := async tools
depends := src/async src/tools

boost_libraries := thread

include $(path_step)/makefile.mak
