binary_name := formats_test_fsb
path_step := ../../../../..
source_dirs := .

libraries.common = binary binary_format debug formats_archived strings tools

windows_libraries := advapi32

include $(path_step)/makefile.mak
