binary_name := formats_test_fsb
dirs.root := ../../../../..
source_dirs := .

libraries.common = binary binary_format debug formats_archived strings tools

libraries.windows := advapi32

include $(dirs.root)/makefile.mak
