binary_name := formats_test_asc
path_step := ../../../../..
source_dirs := .

libraries.common = tools formats_chiptune binary binary_format debug

windows_libraries := advapi32

include $(path_step)/makefile.mak
