binary_name := formats_test_asc
dirs.root := ../../../../..
source_dirs := .

libraries.common = tools formats_chiptune binary binary_format debug strings

libraries.windows := advapi32

include $(dirs.root)/makefile.mak
