binary_name := formats_test_asc
dirs.root := ../../../../..
source_dirs := .

libraries.common = tools formats_chiptune formats_packed binary binary_compression binary_format debug strings

libraries.3rdparty = lhasa unrar zlib

libraries.windows := advapi32

include $(dirs.root)/makefile.mak
