library_name := playlist_ui_desktop
path_step := ../../../../..

source_dirs := .

ui_files := search_dialog properties_dialog no_items_contextmenu single_item_contextmenu multiple_items_contextmenu
moc_files := playlist_contextmenu

ts_files := playlist_ui_desktop

includes.dirs += ../../..

include $(path_step)/makefile.mak
