/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_zxtune_core_jni_NativeModule */

#ifndef _Included_app_zxtune_core_jni_NativeModule
#define _Included_app_zxtune_core_jni_NativeModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_zxtune_core_jni_NativeModule
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_NativeModule_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     app_zxtune_core_jni_NativeModule
 * Method:    getDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_core_jni_NativeModule_getDuration
  (JNIEnv *, jobject);

/*
 * Class:     app_zxtune_core_jni_NativeModule
 * Method:    createPlayerInternal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_core_jni_NativeModule_createPlayerInternal
  (JNIEnv *, jobject);

/*
 * Class:     app_zxtune_core_jni_NativeModule
 * Method:    getProperty
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_app_zxtune_core_jni_NativeModule_getProperty__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     app_zxtune_core_jni_NativeModule
 * Method:    getProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_zxtune_core_jni_NativeModule_getProperty__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     app_zxtune_core_jni_NativeModule
 * Method:    getAdditionalFiles
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_app_zxtune_core_jni_NativeModule_getAdditionalFiles
  (JNIEnv *, jobject);

/*
 * Class:     app_zxtune_core_jni_NativeModule
 * Method:    resolveAdditionalFileInternal
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_NativeModule_resolveAdditionalFileInternal
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
