/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_zxtune_core_jni_JniApi */

#ifndef _Included_app_zxtune_core_jni_JniApi
#define _Included_app_zxtune_core_jni_JniApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_zxtune_core_jni_JniApi
 * Method:    forcedInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniApi_forcedInit
  (JNIEnv *, jobject);

/*
 * Class:     app_zxtune_core_jni_JniApi
 * Method:    loadModule
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)Lapp/zxtune/core/Module;
 */
JNIEXPORT jobject JNICALL Java_app_zxtune_core_jni_JniApi_loadModule
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     app_zxtune_core_jni_JniApi
 * Method:    detectModules
 * Signature: (Ljava/nio/ByteBuffer;Lapp/zxtune/core/jni/DetectCallback;Lapp/zxtune/utils/ProgressCallback;)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniApi_detectModules
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     app_zxtune_core_jni_JniApi
 * Method:    enumeratePlugins
 * Signature: (Lapp/zxtune/core/jni/Plugins/Visitor;)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniApi_enumeratePlugins
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_core_jni_JniApi_LoggingOptionsAdapter */

#ifndef _Included_app_zxtune_core_jni_JniApi_LoggingOptionsAdapter
#define _Included_app_zxtune_core_jni_JniApi_LoggingOptionsAdapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
