/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_zxtune_core_jni_JniModule */

#ifndef _Included_app_zxtune_core_jni_JniModule
#define _Included_app_zxtune_core_jni_JniModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_zxtune_core_jni_JniModule
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniModule_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     app_zxtune_core_jni_JniModule
 * Method:    getDurationMs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_core_jni_JniModule_getDurationMs
  (JNIEnv *, jobject);

/*
 * Class:     app_zxtune_core_jni_JniModule
 * Method:    createPlayer
 * Signature: (I)Lapp/zxtune/core/Player;
 */
JNIEXPORT jobject JNICALL Java_app_zxtune_core_jni_JniModule_createPlayer
  (JNIEnv *, jobject, jint);

/*
 * Class:     app_zxtune_core_jni_JniModule
 * Method:    getProperty
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_app_zxtune_core_jni_JniModule_getProperty__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     app_zxtune_core_jni_JniModule
 * Method:    getProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_zxtune_core_jni_JniModule_getProperty__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     app_zxtune_core_jni_JniModule
 * Method:    getProperty
 * Signature: (Ljava/lang/String;[B)[B;
 */
JNIEXPORT jbyteArray JNICALL Java_app_zxtune_core_jni_JniModule_getProperty__Ljava_lang_String_2_3B
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     app_zxtune_core_jni_JniModule
 * Method:    getAdditionalFiles
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_app_zxtune_core_jni_JniModule_getAdditionalFiles
  (JNIEnv *, jobject);

/*
 * Class:     app_zxtune_core_jni_JniModule
 * Method:    resolveAdditionalFile
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniModule_resolveAdditionalFile
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
