/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_zxtune_core_jni_JniPlayer */

#ifndef _Included_app_zxtune_core_jni_JniPlayer
#define _Included_app_zxtune_core_jni_JniPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_zxtune_core_jni_JniPlayer
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniPlayer_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     app_zxtune_core_jni_JniPlayer
 * Method:    render
 * Signature: ([S)Z
 */
JNIEXPORT jboolean JNICALL Java_app_zxtune_core_jni_JniPlayer_render
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     app_zxtune_core_jni_JniPlayer
 * Method:    analyze
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_core_jni_JniPlayer_analyze
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     app_zxtune_core_jni_JniPlayer
 * Method:    getPositionMs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_core_jni_JniPlayer_getPositionMs
  (JNIEnv *, jobject);

/*
 * Class:     app_zxtune_core_jni_JniPlayer
 * Method:    setPositionMs
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniPlayer_setPositionMs
  (JNIEnv *, jobject, jint);

/*
 * Class:     app_zxtune_core_jni_JniPlayer
 * Method:    getPerformance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_core_jni_JniPlayer_getPerformance
  (JNIEnv *, jobject);

/*
 * Class:     app_zxtune_core_jni_JniPlayer
 * Method:    getProgress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_core_jni_JniPlayer_getProgress
  (JNIEnv *, jobject);

/*
 * Class:     app_zxtune_core_jni_JniPlayer
 * Method:    setProperty
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniPlayer_setProperty__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     app_zxtune_core_jni_JniPlayer
 * Method:    setProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniPlayer_setProperty__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
