/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_zxtune_core_jni_JniOptions */

#ifndef _Included_app_zxtune_core_jni_JniOptions
#define _Included_app_zxtune_core_jni_JniOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_zxtune_core_jni_JniOptions
 * Method:    setProperty
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniOptions_setProperty__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     app_zxtune_core_jni_JniOptions
 * Method:    setProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_core_jni_JniOptions_setProperty__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     app_zxtune_core_jni_JniOptions
 * Method:    getProperty
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_app_zxtune_core_jni_JniOptions_getProperty__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     app_zxtune_core_jni_JniOptions
 * Method:    getProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_zxtune_core_jni_JniOptions_getProperty__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_core_jni_JniOptions_Holder */

#ifndef _Included_app_zxtune_core_jni_JniOptions_Holder
#define _Included_app_zxtune_core_jni_JniOptions_Holder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
