/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_zxtune_ZXTune */

#ifndef _Included_app_zxtune_ZXTune
#define _Included_app_zxtune_ZXTune
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_zxtune_ZXTune
 * Method:    Module_Create
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_ZXTune_Module_1Create
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Module_Detect
 * Signature: (Ljava/nio/ByteBuffer;Lapp/zxtune/ZXTune/ModuleDetectCallbackNativeAdapter;)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_ZXTune_Module_1Detect
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_ZXTune_ModuleDetectCallback */

#ifndef _Included_app_zxtune_ZXTune_ModuleDetectCallback
#define _Included_app_zxtune_ZXTune_ModuleDetectCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_ZXTune_ModuleDetectCallbackNativeAdapter */

#ifndef _Included_app_zxtune_ZXTune_ModuleDetectCallbackNativeAdapter
#define _Included_app_zxtune_ZXTune_ModuleDetectCallbackNativeAdapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
