binary_name := psfdump
path_step := ../../..
source_dirs := .

libraries.common = binary binary_compression binary_format debug formats_chiptune strings tools

libraries.3rdparty = zlib

libraries.windows += advapi32

include $(path_step)/makefile.mak
