binary_name := cmd_test
path_step := ../..
source_dirs := .

libraries := snd_supp zxtune platform_supp

dynamic_libs := pthread asound

depends := lib supp platform

include_path := $(path_step)/lib/include

#definitions := WAVE

include $(path_step)/makefile.mak
