binary_name := cmd_test
path_step := ../..
source_dirs := .

libraries := platform_supp
solid_libs := zxtune snd_supp
dynamic_libs := pthread asound

depends := src/lib src/supp src/platform

include_path := $(path_step)/src/lib/include

include $(path_step)/makefile.mak
