binary_name := cmd_test
path_step := ../..
source_dirs := .

libraries := snd_supp platform_supp
solid_libs := zxtune
dynamic_libs := pthread asound

depends := src/lib src/supp src/platform

include_path := $(path_step)/src/lib/include

include $(path_step)/makefile.mak
