all test:
	$(MAKE) -C common $(MAKECMDGOALS)
	$(MAKE) -C error $(MAKECMDGOALS)
	$(MAKE) -C lazy $(MAKECMDGOALS)
	$(MAKE) -C source_location $(MAKECMDGOALS)
	$(MAKE) -C static_string $(MAKECMDGOALS)
