binary_name := formats_test_hrum
path_step := ../../../..
source_files := test

libraries := io formats binary
depends := src/formats src/binary src/io

windows_libraries := advapi32

include $(path_step)/makefile.mak
