library_name := platform_version
path_step := ../../..
include $(path_step)/make/default.mak

source_dirs := src

text_files := text/text

defines += BUILD_VERSION=$(root.version)

include $(path_step)/makefile.mak
include $(path_step)/make/version.mak
