library_name := platform_version
dirs.root := ../../..
include $(dirs.root)/make/default.mak

source_dirs := src

defines += BUILD_VERSION=$(root.version)

jumbo.name := $(library_name)

include $(dirs.root)/makefile.mak
include $(dirs.root)/make/version.mak
