binary_name := formats_test_s98
dirs.root := ../../../../..
source_dirs := .

libraries.common = binary binary_compression binary_format debug formats_chiptune strings tools

libraries.windows := advapi32

include $(dirs.root)/makefile.mak
