// This file was automatically generated
#ifndef __TEXT_CHIPTUNE_H_DEFINED__
#define __TEXT_CHIPTUNE_H_DEFINED__
#include <char_type.h>

namespace Text
{
extern const Char ASCSOUNDMASTER0_DECODER_DESCRIPTION[];
extern const Char ASCSOUNDMASTER1_DECODER_DESCRIPTION[];
extern const Char ASCSOUNDMASTER2_DECODER_DESCRIPTION[];
extern const Char AY_EMUL_DECODER_DESCRIPTION[];
extern const Char CHIPTRACKER_DECODER_DESCRIPTION[];
extern const Char CHIPTRACKER_EDITOR[];
extern const Char DIGITALMUSICMAKER_DECODER_DESCRIPTION[];
extern const Char DIGITALSTUDIO_DECODER_DESCRIPTION[];
extern const Char DIGITALSTUDIO_VERSION_AY[];
extern const Char DIGITALSTUDIO_VERSION_DAC[];
extern const Char ETRACKER_DECODER_DESCRIPTION[];
extern const Char FASTTRACKER_DECODER_DESCRIPTION[];
extern const Char GLOBALTRACKER1_EDITOR[];
extern const Char GLOBALTRACKER_DECODER_DESCRIPTION[];
extern const Char PRODIGITRACKER_DECODER_DESCRIPTION[];
extern const Char PROSOUNDCREATOR_DECODER_DESCRIPTION[];
extern const Char PROSOUNDCREATOR_EDITOR[];
extern const Char PROSOUNDCREATOR_EDITOR_NEW[];
extern const Char PROSOUNDCREATOR_EDITOR_OLD[];
extern const Char PROSOUNDMAKER_DECODER_DESCRIPTION[];
extern const Char PROTRACKER1_DECODER_DESCRIPTION[];
extern const Char PROTRACKER24_DECODER_DESCRIPTION[];
extern const Char PROTRACKER2_DECODER_DESCRIPTION[];
extern const Char PROTRACKER3_DECODER_DESCRIPTION[];
extern const Char PROTRACKERUTILITY13_DECODER_DESCRIPTION[];
extern const Char PSG_DECODER_DESCRIPTION[];
extern const Char SAMPLETRACKER_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKER3_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKERCOMPILED_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKERPRO2_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKERPROCOMPILED_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKERPRO_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKER_DECODER_DESCRIPTION[];
extern const Char SQDIGITALTRACKER_DECODER_DESCRIPTION[];
extern const Char SQTRACKER_DECODER_DESCRIPTION[];
extern const Char TFC_DECODER_DESCRIPTION[];
extern const Char TFD_DECODER_DESCRIPTION[];
extern const Char TFMMUSICMAKER05_DECODER_DESCRIPTION[];
extern const Char TFMMUSICMAKER13_DECODER_DESCRIPTION[];
extern const Char VORTEXTRACKER2_DECODER_DESCRIPTION[];
extern const Char VORTEX_EDITOR[];
extern const Char VTX_DECODER_DESCRIPTION[];
extern const Char YM_DECODER_DESCRIPTION[];
}//namespace Text
#endif //__TEXT_CHIPTUNE_H_DEFINED__
