// This file was automatically generated
#ifndef __TEXT_CHIPTUNE_H_DEFINED__
#define __TEXT_CHIPTUNE_H_DEFINED__
#include <char_type.h>

namespace Text
{
extern const Char ASCSOUNDMASTER0_DECODER_DESCRIPTION[];
extern const Char ASCSOUNDMASTER1_DECODER_DESCRIPTION[];
extern const Char ASCSOUNDMASTER2_DECODER_DESCRIPTION[];
extern const Char DIGITALSTUDIO_DECODER_DESCRIPTION[];
extern const Char FASTTRACKER_DECODER_DESCRIPTION[];
extern const Char GLOBALTRACKER1_EDITOR[];
extern const Char GLOBALTRACKER_DECODER_DESCRIPTION[];
extern const Char PROSOUNDMAKER_DECODER_DESCRIPTION[];
extern const Char PROTRACKER1_DECODER_DESCRIPTION[];
extern const Char PROTRACKER24_DECODER_DESCRIPTION[];
extern const Char PROTRACKER2_DECODER_DESCRIPTION[];
extern const Char PROTRACKER3_DECODER_DESCRIPTION[];
extern const Char PROTRACKERUTILITY13_DECODER_DESCRIPTION[];
extern const Char PSG_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKERCOMPILED_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKERPRO2_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKERPROCOMPILED_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKERPRO_DECODER_DESCRIPTION[];
extern const Char SOUNDTRACKER_DECODER_DESCRIPTION[];
extern const Char TFC_DECODER_DESCRIPTION[];
extern const Char TFD_DECODER_DESCRIPTION[];
extern const Char VTX_DECODER_DESCRIPTION[];
extern const Char YM_DECODER_DESCRIPTION[];
}//namespace Text
#endif //__TEXT_CHIPTUNE_H_DEFINED__
