binary_name := formats_test_hrip
path_step := ../../../..
source_files := test

libraries := formats_archived formats_packed binary
depends := src/formats/archived src/formats/packed src/binary

include $(path_step)/makefile.mak
