binary_name := formats_test_gzip
path_step := ../../../..
source_dirs := .

libraries.common = binary binary_compression binary_format formats_packed tools

libraries.3rdparty = zlib

include $(path_step)/makefile.mak
