binary_name := formats_test_gzip
dirs.root := ../../../..
source_dirs := .

libraries.common = binary binary_compression binary_format formats_packed tools

libraries.3rdparty = zlib

include $(dirs.root)/makefile.mak
