#stub library for archives functionality without formats_packed linking
library_name := formats_packed_archives
path_step := ../../../..
source_files := ../lha_file.cpp ../rar_file.cpp ../zip_file.cpp ../gzip.cpp

include $(path_step)/make/default.mak

include $(path_step)/makefile.mak
