#stub library for archives functionality without formats_packed linking
library_name := formats_packed_archives
dirs.root := ../../../..
source_files := ../lha_file.cpp ../rar_file.cpp ../zip_file.cpp ../gzip.cpp ../zxzip_file.cpp ../hrust2.cpp

include $(dirs.root)/make/default.mak

jumbo.name := $(library_name)

include $(dirs.root)/makefile.mak
