library_name := module_players
path_step := ../../..
source_dirs := . aym dac saa tfm xsf

po_files := module_players

include $(path_step)/3rdparty/ao/defines.mak

include $(path_step)/makefile.mak

