library_name := module_players
dirs.root := ../../..
source_dirs := . aym dac saa tfm xsf

po_files := module_players

include $(dirs.root)/3rdparty/mgba/defines.mak

include $(dirs.root)/makefile.mak

