library_name := formats
path_step := ../..
source_dirs := packed

#temporary reference until full code movement
include_dirs := $(path_step)/src/core/plugins/archives

include $(path_step)/makefile.mak
