library_name := formats
path_step := ../..
source_dirs := archived chiptune packed

include $(path_step)/make/default.mak

text_files := text/archived text/chiptune text/packed

$(platform)_include_dirs += $(path_step)/3rdparty

include $(path_step)/makefile.mak
