/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_zxtune_ZXTune */

#ifndef _Included_app_zxtune_ZXTune
#define _Included_app_zxtune_ZXTune
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_zxtune_ZXTune
 * Method:    Data_Create
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_ZXTune_Data_1Create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Data_Destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_ZXTune_Data_1Destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Module_Create
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_ZXTune_Module_1Create
  (JNIEnv *, jclass, jint);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Module_Destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_ZXTune_Module_1Destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    ModuleInfo_GetFramesCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_ZXTune_ModuleInfo_1GetFramesCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Module_GetProperty
 * Signature: (ILjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_app_zxtune_ZXTune_Module_1GetProperty__ILjava_lang_String_2J
  (JNIEnv *, jclass, jint, jstring, jlong);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Module_GetProperty
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_zxtune_ZXTune_Module_1GetProperty__ILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Player_Create
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_ZXTune_Player_1Create
  (JNIEnv *, jclass, jint);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Player_Destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_ZXTune_Player_1Destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Player_Render
 * Signature: (ILjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_app_zxtune_ZXTune_Player_1Render
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Player_GetPosition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_app_zxtune_ZXTune_Player_1GetPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Player_GetProperty
 * Signature: (ILjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_app_zxtune_ZXTune_Player_1GetProperty__ILjava_lang_String_2J
  (JNIEnv *, jclass, jint, jstring, jlong);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Player_GetProperty
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_zxtune_ZXTune_Player_1GetProperty__ILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Player_SetProperty
 * Signature: (ILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_ZXTune_Player_1SetProperty__ILjava_lang_String_2J
  (JNIEnv *, jclass, jint, jstring, jlong);

/*
 * Class:     app_zxtune_ZXTune
 * Method:    Player_SetProperty
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_app_zxtune_ZXTune_Player_1SetProperty__ILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_ZXTune_Properties */

#ifndef _Included_app_zxtune_ZXTune_Properties
#define _Included_app_zxtune_ZXTune_Properties
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_ZXTune_Properties_Accessor */

#ifndef _Included_app_zxtune_ZXTune_Properties_Accessor
#define _Included_app_zxtune_ZXTune_Properties_Accessor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_ZXTune_Properties_Modifier */

#ifndef _Included_app_zxtune_ZXTune_Properties_Modifier
#define _Included_app_zxtune_ZXTune_Properties_Modifier
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_ZXTune_NativeObject */

#ifndef _Included_app_zxtune_ZXTune_NativeObject
#define _Included_app_zxtune_ZXTune_NativeObject
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_ZXTune_Data */

#ifndef _Included_app_zxtune_ZXTune_Data
#define _Included_app_zxtune_ZXTune_Data
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_ZXTune_Module */

#ifndef _Included_app_zxtune_ZXTune_Module
#define _Included_app_zxtune_ZXTune_Module
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_ZXTune_Module_Attributes */

#ifndef _Included_app_zxtune_ZXTune_Module_Attributes
#define _Included_app_zxtune_ZXTune_Module_Attributes
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class app_zxtune_ZXTune_Player */

#ifndef _Included_app_zxtune_ZXTune_Player
#define _Included_app_zxtune_ZXTune_Player
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
