library_name := formats_packed
dirs.root := ../../..
source_dirs := .

include $(dirs.root)/make/default.mak

text_files := ../text/packed

jumbo.name := $(library_name)

include $(dirs.root)/makefile.mak
