library_name := formats_packed
path_step := ../../..
source_dirs := .

include $(path_step)/make/default.mak

text_files := ../text/packed

$(platform)_include_dirs += $(path_step)/3rdparty

include $(path_step)/makefile.mak
