library_name := formats_packed
dirs.root := ../../..
source_dirs := archives common decompilers images snapshots zx

include $(dirs.root)/make/default.mak

jumbo.name := $(library_name)

include $(dirs.root)/makefile.mak
