library_name := ui_preferences
path_step := ../../../..

ui_files = aym mixer mixing plugins sound z80 preferencesdialog

ui_files += sound_alsa

include_dirs = ../..

include $(path_step)/makefile.mak
