library_name := ui_preferences
dirs.root := ../../../..

source_dirs := .

ui_files = aym mixer mixing plugins sound saa sid z80 interface preferencesdialog

ui_files += sound_alsa sound_dsound sound_oss sound_sdl sound_win32

ts_files := ui_preferences

include $(dirs.root)/makefile.mak
