@ECHO OFF

SET QT_VERSION=4.5.3
SET QT_COMMON_DIR=%BUILD_TOOLS_DIR%\Qt\%QT_VERSION%
SET QT_DIR=%QT_COMMON_DIR%-%MSVS_VERSION%

ECHO %PATH% | FIND "%QT_DIR%" > NUL && GOTO Quit

:: Lets use 32-bit binaries anyway
SET QT_BIN=%QT_DIR%\bin
SET QT_LIB=%QT_DIR%\lib%1%
SET PATH=%QT_BIN%;%PATH%
SET LIB=%QT_LIB%;%LIB%
SET INCLUDE=%QT_COMMON_DIR%\include;%INCLUDE%
SET QT_BIN=
SET QT_LIB=
:Quit
