@ECHO OFF

SET QT_VERSION=4.5.3
SET QT_DIR=%CD:~0,2%\Build\Qt\%QT_VERSION%-%MSVS_VERSION%

ECHO %PATH% | FIND "%QT_DIR%" > NUL && GOTO Quit

SET PATH=%QT_DIR%\bin;%PATH%
SET LIB=%QT_DIR%\lib;%LIB%
SET INCLUDE=%QT_DIR%\include;%INCLUDE%
:Quit
