@echo off

SET VS_PATH=%PROGRAMFILES%\Microsoft Visual Studio 8
ECHO %PATH% | FIND "%VS_PATH%" > NUL && GOTO Quit
SET BOOST_VERSION=1_40
SET BOOST_DIR=c:\Boost_%BOOST_VERSION%
SET PATH=%VS_PATH%\VC\bin;%VS_PATH%\Common7\IDE;%PATH%
SET LIB=%BOOST_DIR%\lib;%VS_PATH%\VC\lib;%VS_PATH%\VC\PlatformSDK\Lib
SET INCLUDE=%BOOST_DIR%;%VS_PATH%\VC\include;%VS_PATH%\VC\PlatformSDK\Include
SET MSVS_VERSION=vc80
:Quit
