@ECHO OFF

SET VS_PATH=%PROGRAMFILES%\Microsoft Visual Studio .NET 2003
ECHO %PATH% | FIND "%VS_PATH%" > NUL && GOTO Quit
SET BOOST_VERSION=1_40
SET BOOST_DIR=c:\Boost_%BOOST_VERSION%
SET PATH=%VS_PATH%\Vc7\bin;%VS_PATH%\Common7\IDE;%PATH%
SET LIB=%BOOST_DIR%\lib;%VS_PATH%\Vc7\lib;%VS_PATH%\Vc7\PlatformSDK\Lib
SET INCLUDE=%BOOST_DIR%;%VS_PATH%\Vc7\include;%VS_PATH%\Vc7\PlatformSDK\Include
SET MSVS_VERSION=vc71
:Quit
