binary_name := io_file_test
path_step := ../..
source_files := test

libraries := io tools texts
depends := src/tools text src/io

windows_libraries := advapi32.lib

include $(path_step)/makefile.mak
