binary_name := depacker
path_step := ../../..
source_dirs := .

libraries.common = binary binary_compression binary_format debug formats_packed tools

libraries.3rdparty = lhasa zlib

include $(path_step)/makefile.mak
