binary_name := depacker
dirs.root := ../../..
source_dirs := .

libraries.common = binary binary_compression binary_format debug formats_packed tools

libraries.3rdparty = lhasa zlib

include $(dirs.root)/makefile.mak
