library_name := core
path_step := ../..
source_dirs := plugins src

text_files := text/core text/plugins
po_files := core
po_source_dirs := src plugins plugins/players/ay plugins/containers

include $(path_step)/makefile.mak
