library_name := core
path_step := ../..
source_dirs := parameters \
               plugins \
               plugins/archives \
               plugins/containers \
               plugins/players \
               plugins/players/ay \
               plugins/players/dac \
               plugins/players/tfm \
               src

text_files := text/core text/plugins text/warnings

include $(path_step)/makefile.mak
