binary_name := formats_test_cc3
path_step := ../../../..
source_files := test

libraries := io formats tools
depends := src/tools src/io src/tools

windows_libraries := advapi32

include $(path_step)/makefile.mak
