#stub library for lha functionality without formats_packed linking
library_name := formats_packed_decompilers
dirs.root := ../../../..
source_files := $(wildcard ../compiled*) ../container.cpp

include $(dirs.root)/make/default.mak

text_files := ../../text/packed

include $(dirs.root)/makefile.mak
