#stub library for lha functionality without formats_packed linking
library_name := formats_packed_decompilers
path_step := ../../../..
source_files := $(addprefix ../compiled,asc pt2 ptu13 st3 stp)

include $(path_step)/make/default.mak

text_files := ../../text/packed

include $(path_step)/makefile.mak
