#all applications increasing dependencies
all:
	$(MAKE) -C benchmark $(MAKECMDGOALS)
	$(MAKE) -C xtractor $(MAKECMDGOALS)
#	$(MAKE) -C libzxtune $(MAKECMDGOALS)
	$(MAKE) -C zxtune123 $(MAKECMDGOALS)
	$(MAKE) -C zxtune-qt $(MAKECMDGOALS)
