binary_name := formats_test_esv
dirs.root := ../../../..
source_dirs := .

libraries.common = binary binary_compression binary_format formats_chiptune formats_packed debug strings tools

libraries.3rdparty = lhasa unrar zlib

include $(dirs.root)/makefile.mak
