binary_name := formats_test_sndh
dirs.root := ../../../../..
source_dirs := .

libraries.common = binary binary_format debug formats_chiptune formats_multitrack strings tools

libraries.windows := advapi32

include $(dirs.root)/makefile.mak
