binary_name := scan_format
path_step := ../../../..
source_files := main

libraries := binary debug io l10n_stub platform tools 
depends := src/binary src/debug src/io src/l10n/stub src/platform src/tools
boost_libraries := filesystem system

windows_libraries = advapi32

include $(path_step)/makefile.mak
