binary_name := scan_format
path_step := ../../../..
source_dirs := .

libraries.common = binary binary_format debug io l10n_stub parameters platform strings tools 

libraries.boost = filesystem system

windows_libraries = advapi32

include $(path_step)/makefile.mak
