binary_name := scan_format
path_step := ../../../..
source_files := main

libraries.common = binary debug io l10n_stub platform tools 

libraries.boost = filesystem system

windows_libraries = advapi32

include $(path_step)/makefile.mak
