binary_name := sound_test_platform
path_step := ../../../..
source_files := test

libraries := async io sound tools
depends := src/async src/io src/sound src/tools

boost_libraries := thread

include $(path_step)/makefile.mak
