binary_name := sound_test_platform
dirs.root := ../../../..
source_dirs := .

libraries.common = async binary debug l10n_stub platform strings sound sound_backends tools

libraries.windows = ole32
libraries.mingw = ole32

include $(dirs.root)/makefile.mak
