binary_name := sound_test_platform
path_step := ../../../..
source_files := test

libraries.common = async binary debug io l10n_stub platform strings sound sound_backends tools

libraries.boost = filesystem system thread

windows_libraries = ole32
mingw_libraries = ole32

include $(path_step)/makefile.mak
