name: CI Linux

on: [push, pull_request]

jobs:
  build:
    name: Linux (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: [Debug, Release]
        include:
          - generator: Ninja
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install build-essential g++ cmake ninja-build libsdl2-dev
    - name: Build Shared
      run: |
        mkdir build
        cd build
        cmake -G ${{ matrix.generator }} -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ..
        cmake --build .
        cmake --build . --target demo
        cmake --build . --target demo_mem
        cmake --build . --target demo_multi
        cmake --build . --target gme_player
    - name: Build Static
      run: |
        mkdir build-static
        cd build-static
        cmake -G ${{ matrix.generator }} -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DBUILD_SHARED_LIBS=OFF ..
        cmake --build .
        cmake --build . --target demo
        cmake --build . --target demo_mem
        cmake --build . --target demo_multi
        cmake --build . --target gme_player
