binary_name := l10n_test_boost_locale
path_step := ../../../..
source_dirs := .

include $(path_step)/make/default.mak

libraries.common = debug l10n tools

libraries.boost := locale
mingw_libraries := iconv

include $(path_step)/makefile.mak
