// Generated from '$Id$'
#ifndef __TEXT_CORE_H_DEFINED__
#define __TEXT_CORE_H_DEFINED__
#include <char_type.h>

extern const Char TEXT_MODULE_CONTAINERS_DELIMITER[];
extern const Char TEXT_MODULE_ERROR_CANCELED[];
extern const Char TEXT_MODULE_ERROR_CONVERSION_UNSUPPORTED[];
extern const Char TEXT_MODULE_ERROR_CONVERT_PSG[];
extern const Char TEXT_MODULE_ERROR_FIND_SUBMODULE[];
extern const Char TEXT_MODULE_ERROR_INVALID_FORMAT[];
extern const Char TEXT_MODULE_ERROR_INVALID_FREQ_TABLE_NAME[];
extern const Char TEXT_MODULE_ERROR_INVALID_FREQ_TABLE_SIZE[];
extern const Char TEXT_MODULE_ERROR_MODULE_END[];
extern const Char TEXT_MODULE_ERROR_PARAMETERS[];
extern const Char TEXT_MODULE_ERROR_SET_PLAYER_PARAMETERS[];
extern const Char TEXT_MODULE_MESSAGE_DETECT_IMPLICIT[];
extern const Char TEXT_MODULE_MESSAGE_DETECT_PLAYER[];
extern const Char TEXT_MODULE_MESSAGE_OPEN_IMPLICIT[];
extern const Char TEXT_MODULE_MESSAGE_OPEN_NESTED[];
extern const Char TEXT_PLUGIN_RAW_MESSAGE_PROGRESS[];
#endif //__TEXT_CORE_H_DEFINED__
