// Generated from '$Id$'
#ifndef __TEXT_SOUND_H_DEFINED__
#define __TEXT_SOUND_H_DEFINED__
#include <char_type.h>

extern const Char TEXT_SOUND_ERROR_BACKEND_FAILED[];
extern const Char TEXT_SOUND_ERROR_BACKEND_INVALID_CHANNELS[];
extern const Char TEXT_SOUND_ERROR_BACKEND_INVALID_FILTER[];
extern const Char TEXT_SOUND_ERROR_BACKEND_INVALID_GAIN[];
extern const Char TEXT_SOUND_ERROR_BACKEND_INVALID_MODULE[];
extern const Char TEXT_SOUND_ERROR_BACKEND_INVALID_STATE[];
extern const Char TEXT_SOUND_ERROR_BACKEND_NOT_FOUND[];
extern const Char TEXT_SOUND_ERROR_BACKEND_NO_MEMORY[];
extern const Char TEXT_SOUND_ERROR_BACKEND_PAUSE[];
extern const Char TEXT_SOUND_ERROR_BACKEND_PLAYBACK[];
extern const Char TEXT_SOUND_ERROR_BACKEND_SEEK[];
extern const Char TEXT_SOUND_ERROR_BACKEND_SETUP_BACKEND[];
extern const Char TEXT_SOUND_ERROR_BACKEND_STOP[];
extern const Char TEXT_SOUND_ERROR_BACKEND_UNSUPPORTED_VOLUME[];
extern const Char TEXT_SOUND_ERROR_FILTER_HIGH_CUTOFF[];
extern const Char TEXT_SOUND_ERROR_FILTER_LOW_CUTOFF[];
extern const Char TEXT_SOUND_ERROR_FILTER_ORDER[];
extern const Char TEXT_SOUND_ERROR_MIXER_INVALID_MATRIX_CHANNELS[];
extern const Char TEXT_SOUND_ERROR_MIXER_INVALID_MATRIX_GAIN[];
extern const Char TEXT_SOUND_ERROR_MIXER_UNSUPPORTED[];
#endif //__TEXT_SOUND_H_DEFINED__
