// Generated from '$Id$'
#ifndef __TEXT_WARNINGS_H_DEFINED__
#define __TEXT_WARNINGS_H_DEFINED__
#include <char_type.h>

extern const Char TEXT_CHANNEL_WARN_PREFIX[];
extern const Char TEXT_LINE_CHANNEL_WARN_PREFIX[];
extern const Char TEXT_LINE_WARN_PREFIX[];
extern const Char TEXT_ORNAMENT_WARN_PREFIX[];
extern const Char TEXT_PATTERN_WARN_PREFIX[];
extern const Char TEXT_SAMPLE_WARN_PREFIX[];
extern const Char TEXT_WARNING_DUPLICATE_ENVELOPE[];
extern const Char TEXT_WARNING_DUPLICATE_NOISEBASE[];
extern const Char TEXT_WARNING_DUPLICATE_NOTE[];
extern const Char TEXT_WARNING_DUPLICATE_ORNAMENT[];
extern const Char TEXT_WARNING_DUPLICATE_SAMPLE[];
extern const Char TEXT_WARNING_DUPLICATE_STATE[];
extern const Char TEXT_WARNING_DUPLICATE_TEMPO[];
extern const Char TEXT_WARNING_DUPLICATE_VOLUME[];
extern const Char TEXT_WARNING_INVALID_CHANNEL[];
extern const Char TEXT_WARNING_INVALID_LENGTH[];
extern const Char TEXT_WARNING_INVALID_NOISE_BASE[];
extern const Char TEXT_WARNING_INVALID_NOTE_GLISS[];
extern const Char TEXT_WARNING_INVALID_ORNAMENT[];
extern const Char TEXT_WARNING_INVALID_ORNAMENT_OFFSET[];
extern const Char TEXT_WARNING_INVALID_PATTERN[];
extern const Char TEXT_WARNING_INVALID_PATTERN_SIZE[];
extern const Char TEXT_WARNING_INVALID_POSITIONS[];
extern const Char TEXT_WARNING_INVALID_SAMPLE[];
extern const Char TEXT_WARNING_INVALID_SAMPLE_OFFSET[];
extern const Char TEXT_WARNING_LOOP_OUT_BOUND[];
extern const Char TEXT_WARNING_LOOP_OUT_LIMIT[];
extern const Char TEXT_WARNING_PERIODS[];
extern const Char TEXT_WARNING_TOO_LONG[];
extern const Char TEXT_WARNING_UNEXPECTED_END[];
extern const Char TEXT_WARNING_UNSUPPORTED_COMMAND[];
#endif //__TEXT_WARNINGS_H_DEFINED__
