binary_name := formats_test_spc
path_step := ../../../../..
source_dirs := .

libraries.common = binary binary_format debug formats_chiptune strings tools

windows_libraries := advapi32

include $(path_step)/makefile.mak
