library_name := formats_archived_multitrack
path_step := ../../../..
source_files := ../multiay

include $(path_step)/make/default.mak

text_files := ../../text/archived

include $(path_step)/makefile.mak
