library_name := formats_archived_multitrack
dirs.root := ../../../..
source_dirs = .

include $(dirs.root)/make/default.mak

text_files := ../../text/archived

jumbo.name := $(library_name)

include $(dirs.root)/makefile.mak
