library_name := formats_chiptune
dirs.root := ../../..
source_dirs := . aym digital emulation fm multidevice multitrack music saa

text_files := ../text/chiptune

include $(dirs.root)/makefile.mak
