library_name := formats_chiptune
path_step := ../../..
source_dirs := . aym digital emulation fm multidevice multitrack music saa

text_files := ../text/chiptune

include $(path_step)/makefile.mak
