library_name := formats_chiptune
dirs.root := ../../..
source_dirs := . aym digital emulation fm multidevice multitrack music saa

jumbo.name := $(library_name)

include $(dirs.root)/makefile.mak
